owner: MoBeStudent
repo: Ariwa-Status

sites:
  - name: ARIWA AktivCloud
    url: https://aktivcloud.ariwa.org
  - name: ARIWA Website
    url: https://www.ariwa.org/
  - name: Biowahrheit
    url: https://www.biowahrheit.de/
  - name: Vegan Street Day Stuttgart
    url: https://stuttgart.vegan-street-day.de/
  - name: Vegan Street Day Ruhr
    url: https://ruhr.vegan-street-day.de/

status-website:
  cname: null
  name: ARIWA Systemstatus
  introTitle: "**Systemstatus der ARIWA Webseiten**"
  introMessage: Hier überwachen wir die Erreichbarkeit unserer Plattformen und Aktions-Seiten.
  logoUrl: https://www.ariwa.org/wp-content/uploads/2018/10/ariwa-animal-rights-watch-logo.png
